name: json_draggable
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  giffy_dialog: ^1.8.0
  http: ^0.12.2
  js: ^0.6.2
  firebase_core: ^0.7.0
  firebase_database: ^6.0.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.14
  flutter_launcher_icons: ^0.8.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "Assets/Images/launcher/Play Room.png"
  image_path_android: "Assets/Images/launcher/Play Room.png"
  adaptive_icon_background: "Assets/Images/launcher/Play Room.png"
  adaptive_icon_foreground: "Assets/Images/launcher/Play Room.png"    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - Assets/Images/cloud.png
    - Assets/Images/cloudW.png
    - Assets/Images/drop.png
    - Assets/Images/dropW.png
    - Assets/Images/moon.png
    - Assets/Images/moonW.png
    - Assets/Images/sun.png
    - Assets/Images/sunW.png
    - Assets/Images/forest.png
    - Assets/Images/rigth.png
    - Assets/Images/fence1.png
    - Assets/Images/fence2.png
    - Assets/Images/fence3.png
    - Assets/Images/fence4.png
    - Assets/Images/house1.png
    - Assets/Images/house2.png
    - Assets/Images/house3.png
    - Assets/Images/house4.png
    - Assets/Images/wrong.png
    - Assets/Images/sunrise.jpg
    - Assets/Images/yay.png
    - Assets/Images/kid.png
    - Assets/Images/welcome.png
    - Assets/Images/play.png
    - Assets/Images/ply.png
    - Assets/Images/Pl.png
    - Assets/Images/kids.png
    - Assets/Images/number1.png
    - Assets/Images/number2.png
    - Assets/Images/number3.png
    - Assets/Images/number4.png
    - Assets/Images/numberone.png
    - Assets/Images/numbertwo.png
    - Assets/Images/numberthree.png
    - Assets/Images/numberfour.png
    - Assets/Images/car.png
    - Assets/Images/carshadow.png
    - Assets/Images/plane.png
    - Assets/Images/planeshadow.png
    - Assets/Images/ship.png
    - Assets/Images/shipshadow.png
    - Assets/Images/train.png
    - Assets/Images/trainshadow.png
    - Assets/Images/banana.png
    - Assets/Images/bluebird.png
    - Assets/Images/blueegg.png
    - Assets/Images/cheese.png
    - Assets/Images/Cow.png
    - Assets/Images/crocodile.png
    - Assets/Images/grass.png
    - Assets/Images/greenbird.png
    - Assets/Images/greenegg.png
    - Assets/Images/meat.png
    - Assets/Images/monkey.png
    - Assets/Images/mouse.png
    - Assets/Images/orangebird.png
    - Assets/Images/orangeegg.png
    - Assets/Images/pinkbird.png
    - Assets/Images/pinkegg.png
    - Assets/Images/welcome1.jpg
    - Assets/Images/B1.jpg
    - Assets/Images/B2.jpg
    - Assets/Images/B3.jpg
    - Assets/Images/B4.jpg
    - Assets/Images/B5.jpg
    - Assets/Images/B6.jpg
   
    
    
    

    
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

  fonts:
    - family: Handlee
      fonts:
        - asset: Assets/Fonts/Handlee-Regular.ttf
              
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
